### PR TITLE
GO: Return latest version from GCS that is a full release

### LINKED ISSUE #170: Bazelisk is pulling a non existing release ( 3.5.1 ) when invoked w/o .bazelversion
Invoking `bazelisk build` is attempting to pull a non-existent release.

This afternoon, a handful of xchammer github jobs started failing that used bazelisk. For example:
https://github.com/pinterest/xchammer/pull/259/checks?check_run_id=1168118720

The xchammer CI runs `bazelisk` and we don't have a version specified in the repository. Without the version, it attempts to pull a non-existing URL:
```
2020/09/25 21:40:42 Downloading https://releases.bazel.build/3.5.1/release/bazel-3.5.1-darwin-x86_64...
2020/09/25 21:40:42 could not download Bazel: HTTP GET https://releases.bazel.build/3.5.1/release/bazel-3.5.1-darwin-x86_64 failed with error 404
make: *** [build-impl] Error 1
Error: Process completed with exit code 2.```

I checked on Bazel releases this afternoon, and it looks like there is no `3.5.1` bazel release: https://github.com/bazelbuild/bazel/releases

### PR DESCRIPTION
**Pull request by fweikert**
If `latest-n` was requested, Bazelisk previously only examined the most recent version to see whether it had a release (and not just candidates).
If there was no release, Bazelisk simply returned the second-to-last one without checking whether that version had a release, too.

Now Bazelisk checks the latest versions until it finds one with a release.

Fixes #170
Progress towards #171

### CODE REVIEW

File: repositories/gcs.go [hunk 1]
```diff
@@ -49,14 +49,22 @@ func getVersionHistoryFromGCS(onlyFullReleases bool) ([]string, error) {
...
-		if err != nil {
-			return []string{}, fmt.Errorf("could not list release candidates for latest release: %v", err)
+	// TODO(#171): This algorithm is incorrect if version == 'latest-n' and any of the last n versions (except the last one) does not have a release yet.
+	if onlyFullReleases {
+		for len(sorted) > 0 {
+			lastIndex := len(sorted)-1
+			latestVersion := sorted[lastIndex]
+			_, isRelease, err := listDirectoriesInReleaseBucket(latestVersion + "/release/")
+			if err != nil {
+				return []string{}, fmt.Errorf("could not list release candidates for latest release: %v", err)
```
Comment (philwo) [inline repositories/gcs.go:59]: It's not the "latest" release, as we iterate over the array, right? What about this?

```go
return []string{}, fmt.Errorf("could not list release candidates for %v: %v", latestVersion, err)
```

File: repositories/gcs.go [hunk 2]
```diff
@@ -49,14 +49,22 @@ func getVersionHistoryFromGCS(onlyFullReleases bool) ([]string, error) {
 	available := getVersionsFromGCSPrefixes(prefixes)
 	sorted := versions.GetInAscendingOrder(available)
 
-	if onlyFullReleases && len(sorted) > 0 {
-		latestVersion := sorted[len(sorted)-1]
-		_, isRelease, err := listDirectoriesInReleaseBucket(latestVersion + "/release/")
-		if err != nil {
-			return []string{}, fmt.Errorf("could not list release candidates for latest release: %v", err)
+	// TODO(#171): This algorithm is incorrect if version == 'latest-n' and any of the last n versions (except the last one) does not have a release yet.
```
Comment (philwo) [inline repositories/gcs.go:52]: Just for my understanding, what we would actually want to do here is to basically filter the `sorted` array and remove all entries for which no release version exists, right? But we don't do that, because you think it's too slow due to the number of HTTP requests?

**Review by philwo — APPROVED** [review]

File: repositories/gcs.go (hunk 2 above)
Comment (fweikert) [reply repositories/gcs.go:52]: Yes, that's the problem. But we can work around this by specifying how many of the latest releases we need: #171
