### PR TITLE
Parse .netrc for HTTP Basic authentication credentials when BAZELISK_BASE_URL points to protected resource

### LINKED ISSUE #291: Support using netrc file for bazel downloads in go version
According to my testing done on Windows 10 with Bazelisk 1.11.0, Bazelisk doesn't use the .netrc file for downloading bazel in the go version, but supports it in the python version.

I'd like to request if it's possible to add this support to the go version.

## Testing

For testing I created a small webserver that just prints all headers passed in.
Then I set the following env vars:

- $env:BAZELISK_BASE_URL="http://localhost:3000"
- $env:USE_BAZEL_VERSION="4.1.0"

And fill my C:\Users\<username>\.netrc with the following (also doesn't work when I use a machine specific config):

```netrc
default
login username
password mypassword
```

If I then run any bazelisk command, I can see a request to my test server, but only these headers get set:

| Header | Value |
|:- |:- |
| host | localhost:3000 |
| user-agent | Bazelisk/v1.11.0 |
| accept-encoding | gzip |

## Existing in python version

Support for .netrc was already requested in #247 and implemented for the python version in #269.
It would be awesome if the same feature existed in the go version.

### PR DESCRIPTION
**Pull request by Warchant**
This PR adds support for using .netrc file for getting credentials for Basic HTTP authentication to download bazel from protected resource.

Same as https://github.com/bazelbuild/bazelisk/pull/269 but for Go code.

Fixes #291 
Fixes #269 

Tested with JFrog Artifactory.

### CODE REVIEW

**Comment by Warchant** [comment]
How to add dependency to https://github.com/jdxcode/netrc if it doesn't have tags? >.<

**Comment by minmichail** [comment]
@fweikert sorry for pushing that already, but we will need that feature soon and we would like to use an official release in case review pass

File: httputil/httputil.go [hunk 1]
```diff
@@ -153,8 +183,22 @@ func DownloadBinary(originURL, destDir, destFile string) (string, error) {
...
+			panic(err)
+		}
+
 		log.Printf("Downloading %s...", originURL)
-		resp, err := get(originURL, "")
+
+		var auth string = ""
+		t, err := tryFindNetrcFileCreds(u.Host)
+		if err == nil {
+			// successfully parsed netrc for given host
```
Comment (fweikert) [inline httputil/httputil.go:197]: I'd fail here if the .netrc file exists, but could not be read (for whatever reasons).

Comment (fweikert) [reply httputil/httputil.go:197]: It would also be good to add a log statement regarding whether a .netrc file was read or not

File: httputil/httputil.go [hunk 2]
```diff
@@ -153,8 +183,22 @@ func DownloadBinary(originURL, destDir, destFile string) (string, error) {
 			}
 		}()
 
+		u, err := url.Parse(originURL)
+		if err != nil {
+			// originURL supposed to be valid
+			panic(err)
```
Comment (fweikert) [inline httputil/httputil.go:189]: Please return an error instead

File: httputil/httputil.go [hunk 3]
```diff
@@ -133,6 +138,31 @@ func parseRetryHeader(value string) (time.Duration, error) {
 	return time.Until(t), nil
 }
 
+// Attempt to open ~/.netrc file and find login/password for given machine (Host).
```
Comment (fweikert) [inline httputil/httputil.go:141]: Please start the comment with the function name, otherwise our linter will fail.

File: httputil/httputil.go (hunk 1 above)
Comment (Warchant) [reply httputil/httputil.go:197]: >I'd fail here if the .netrc file exists, but could not be read (for whatever reasons).

.netrc may exist, but may not contain given "Host". In this case we should proceed with normal auth, without a failure, because remote may not have auth at all.

**Comment by Warchant** [comment]
Ping @fweikert

**Review by fweikert — APPROVED** [review]
